### ISSUE TITLE
Extra character when reading from BSA

### ISSUE THREAD

**Issue by hakasapl** [Ryan-rsm-McKenzie/bsa#15]
When iterating through Skyrim SE BSA files, sometimes an extra character seems to be put in place around non-ASCII characters.

For example, the BSA from this mod: https://www.nexusmods.com/skyrimspecialedition/mods/58403

There is a file named: `meshes\syerscote\goldpot01ÃÂ°.nif` That unknown byte when I paste that path resolves to a comma when looking at the entry's name. What is weird is I can extract that file using bsa browser and save it on my filesystem and it does not have that unknown byte, but I see it as soon as I paste the filename into this issue. Also no extra char appears in BSA browser.

This might be an issue with the BSA itself and not the library given that I see this extra character when I paste the path here. If you have any insight that would be much appreciated!

**Comment by Ryan-rsm-McKenzie** [comment]
You're looking at [mojibake](https://en.wikipedia.org/wiki/Mojibake). The real string is `meshes\syerscote\goldpot01苃냂.nif`, which google translate tells me is korean. This string is a mixture of ascii and utf-16, but most software can't pick up on that and guesses [windows-1252](https://en.wikipedia.org/wiki/Windows-1252) instead. This library doesn't make any guarantees about encoding specifically because nonsense like this can happen, and the game will happily accept it.

**Comment by hakasapl** [comment]
Aha, thank you. I will try a different encoding then
