### ISSUE TITLE
Duplicated file when iterating archive

### ISSUE THREAD

**Issue by Guekka** [Ryan-rsm-McKenzie/bsa#7]
When iterating [this archive](https://workupload.com/file/L99eqVR7s9e) (from [WACCF](https://www.nexusmods.com/skyrimspecialedition/mods/18994)) the file `"textures\\weapons\\orcish\\orcisharrow.dds"` is listed twice.

This causes issues in multithreading with two threads trying to open the same file

**Comment by Ryan-rsm-McKenzie** [comment]
You will notice that these two files are different if you check their hashes, so you are not enumerating the same file twice. What is happening, is the archive has been "optimized" to use binary sharing, except whoever wrote the binary sharing algorithm never thought to themselves what would happen if the "embedded file names" flag is enabled as well. So not only are these two files sharing their binary data, they're also sharing their _file names_, which is why you're seeing the "same file" twice.

**Comment by Guekka** [comment]
Thanks. I expected it to be related to binary sharing
